# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "jooojub"

# A description of your site for social meta tag, search engines, and feed.xml
description: "Unkindness pages"

# Tagline near the site title
tagline: "Unkindness pages"

# The subpath of your site, e.g. /blog, for generating urls
baseurl:

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "http://jooojub.github.io"

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About
  url: /about/
- text: Archives
  url: /tags/
- text: Coding Style
  url: /coding-style/

# The shortname for your Disqus site to enable comments.
disqus: jooojub

# Author information - author info at the bottom of the post
author_name: "jooojub"
author_bio: "System s/w engineer"
author_url:  "http://jooojub.github.io"
author_location: "Korea, Suwon"
author_image: /images/authorimage.png

# Sidebar Add banner
banner_url: "http://jooojub.github.io"
banner_image: images/banner.jpg

# Sidebar newsletter widget - add your form action url for MailChimp signup form here
#mailchimp_url: "//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117"

# Social links in the site footer
#twitter_username: "username"
#facebook_username: "username"
#googleplus_username: "+username"
github_username: "jooojub"
#codepen_username: "username"
#dribbble_uername: "username"
#medium_username: "@username"
#instagram_username: "username"
#pinterest_username: "username"
#linkedin_username: "username"

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/blog/page:num/'
gems: [jekyll-paginate]

permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: false
  syntax_highlighter_opts:
    default_lang: c
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
